networks:
  silk-road:
    driver: bridge

services:
  # auth:
  #   build: ./auth
  # core:
  #   build: python3 server_core/main_server.py
  client:
    build: ./client
    container_name: silk-road-client
    volumes:
      - ./client/src:/app/src
      - ./client/requirements.txt:/app/requirements.txt
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - silk-road
    depends_on:
      - server
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
  server:
    container_name: silk-road-server
    ports:
      - "65432:65432"
    build: ./server
    volumes:
      - ./server/src:/app/src
      - ./server/requirements.txt:/app/requirements.txt
      - ./data:/app/data        # Banco SQLite persistente
    networks:
      - silk-road
  database:
    container_name: silk-road-db
    image: nouchka/sqlite3
    volumes:
      - ./data:/db
      - ./database/init-db.sql:/init.sql
    networks:
      - silk-road